build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armhf: ghcr.io/home-assistant/armhf-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
  i386: ghcr.io/home-assistant/i386-base:3.19
labels:
  org.opencontainers.image.title: "Frame Art Manager"
  org.opencontainers.image.description: "Manage your Samsung Frame TV artwork library"
  org.opencontainers.image.source: "https://github.com/billyfw/ha-frame-art-manager"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"
